In [19]:
import tensorflow as tf
from tensorflow.python.framework import ops
from tensorflow.python.ops import gen_nn_ops
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import control_flow_ops
from tensorflow.python.ops import linalg_ops
from tensorflow.python.ops import math_ops
import networkx as nx
import numpy as np
import pandas as pd

dim = 3
signal_dim = 2
batch_size = 1


input = tf.Variable(tf.ones([batch_size,signal_dim,signal_dim, 1]))
filter = tf.Variable(tf.random_normal([signal_dim,1,1,1]))

op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')


init = tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(init)
    print "input"
    print sess.run(input)
    print "filter"
    print sess.run(filter)
    print "op"
    print sess.run(op)


input
[[[[ 1.]
   [ 1.]]

  [[ 1.]
   [ 1.]]]]
filter
[[[[-0.08915101]]]


 [[[ 0.68513739]]]]
op
[[[[ 0.59598637]
   [ 0.59598637]]]]
