#we try to implement powermethod with kmeans: here
http://jmlr.org/proceedings/papers/v37/boutsidis15.pdf

In [4]:
import numpy as np
import scipy as sp
import pandas as pd
import random
import matplotlib.pyplot as plt
import tensorflow as tf

%matplotlib inline

In [7]:
def euclidean_norm(tensor): #need to have this for tf to work
    square_tensor = tf.square(tensor)
    norm_squared = tf.reduce_sum(square_tensor)
    euclidean_norm = tf.sqrt(norm_squared)
    return euclidean_norm

x = np.random.rand(6,6)
eigenValues,eigenVectors = np.linalg.eig(x)
y = eigenVectors[:, eigenValues.argmax()]

print x
print y

[[ 0.92139587  0.1652271   0.56290292  0.23295117  0.56581458  0.38406818]
 [ 0.32946537  0.4732279   0.8363037   0.60032863  0.64249608  0.22248859]
 [ 0.30062847  0.16211029  0.92651952  0.54943284  0.35227909  0.30673422]
 [ 0.06029913  0.19244761  0.48358007  0.11766975  0.4815164   0.83157198]
 [ 0.42746185  0.92213474  0.45224581  0.58889495  0.53999862  0.79928365]
 [ 0.78450378  0.11089908  0.3623496   0.41529215  0.113503    0.04815951]]
[-0.43173130+0.j -0.46813763+0.j -0.36564634+0.j -0.30230642+0.j
 -0.54520051+0.j -0.26856142+0.j]


In [8]:
#now let try to get the first egenvector right with some backprop




dim_graph = len(x)
dim_subspace = 1
    
x = tf.cast(x, tf.float32)
y = tf.cast(y, tf.float32)

f = {}
for i in range(1,dim_subspace+1):
    f["v{}".format(i)] = tf.Variable(tf.random_uniform(shape = [dim_graph,1],
                                                       minval=-1,
                                                       maxval = 1,
                                                       dtype = tf.float32))
y = f["v1"]
   

adjacency_vector = tf.matmul(x, y)
adjacency_vector = adjacency_vector/euclidean_norm(adjacency_vector)

cost = tf.reduce_mean(tf.square(y-adjacency_vector))                
optimizer = tf.train.GradientDescentOptimizer(0.01)

train = optimizer.minimize(loss = cost, var_list = [f["v1"]])

init_op = tf.initialize_all_variables()


sess = tf.Session()
sess.run(init_op)

for i in xrange(1000):
    sess.run(train)
    if i%500==0:
        print sess.run([adjacency_vector, f["v1"]])
#seems to be accurate, though not really fast.

[array([[-0.40823004],
       [-0.35269931],
       [-0.29864204],
       [-0.41975018],
       [-0.62295759],
       [-0.23558012]], dtype=float32), array([[-0.26560271],
       [-0.08050546],
       [ 0.13229793],
       [-0.43441194],
       [-0.30267304],
       [-0.69729996]], dtype=float32)]
[array([[-0.44441736],
       [-0.44454512],
       [-0.34946659],
       [-0.31506976],
       [-0.55342394],
       [-0.27784696]], dtype=float32), array([[-0.45281619],
       [-0.34480271],
       [-0.21312502],
       [-0.33494425],
       [-0.50335008],
       [-0.35751027]], dtype=float32)]


In [ ]:
x = np.random.rand(6,6)



In [18]:
#get diagonal matrix from adjacency matrix
x = np.random.rand(6,6)

    
x = tf.cast(x, tf.float32)

degree_m_inverse = tf.diag(tf.inv(tf.reduce_sum(x,0))) #takes the degree of each vertex and makes diagonal matrix out of it

laplacian = tf.matmul(degree_m_inverse, x)


with tf.Session() as sess:
    print sess.run(laplacian)

[[ 0.22785513  0.14555821  0.05612845  0.34759179  0.21188471  0.29740292]
 [ 0.5355078   0.14117216  0.22006038  0.49822322  0.01076254  0.27726698]
 [ 0.02561609  0.09864324  0.12067869  0.08292868  0.28207865  0.08401302]
 [ 0.16487895  0.059545    0.13016525  0.1525383   0.01845719  0.1508863 ]
 [ 0.05724719  0.05171482  0.27181932  0.23977141  0.16417806  0.08186068]
 [ 0.10703597  0.1562786   0.32428479  0.08411386  0.17231245  0.28296465]]
