In [1]:
import numpy as np
import scipy as sp
import pandas as pd
from joblib import parallel, delayed

Spectral Clustering using Adjacency Matrix and Laplacian:
Adjacency:  optimizes on in group closeness
Laplacian: Average cut
A variant of the Laplacian: Normalized Cut

In general, Laplacian has better behaved/more stable convergenence properties of eigenvectors (makes sense when we are dealing with random graphs).  

TODO
make function for laplacian
make function for adjaceny matrix
make function for non backtracking matrix

make sampling method for blockmodel

make function for power method

make function for power method for subspace

In [2]:
#assume graphs are dictionaries of vertices with entries that are the incident vertices for now, we can change this later.  



#compute laplacian
    #f-Mf

        #averaging function
        
simple_graph = {
    0: [2,3],
    1: [2, 3],
    2: [3], 
    3: [0, 1]
}

simple_graph[1]

vector = np.array([1,1,1,1])

lst = [vector[i] for i in simple_graph[1]]


In [3]:
def AverageOperatorVertex(vertex, vector, graph):
    lst = [vector[i] for i in graph[vertex]]
    answer = np.sum(lst)
    return(answer)

In [4]:
AverageOperator(vertex = 2, vector = np.array([1,2,3,4]), graph = simple_graph)

4

In [5]:

def GraphLaplacian(graph, vector):
    #takes in graph and vector on graph indices, returns new vector
    new_vector = np.empty(len(vector),)
    for i in graph:
        #this step can be parallelized
        new_vector[i] = AverageOperatorVertex(vertex=i, vector = vector, graph = graph)
    return new_vector

In [6]:
GraphLaplacian(simple_graph, np.array([1,1,1,1]))

array([ 2.,  2.,  1.,  2.])

In [70]:
#Power Method

def PowerMethod(graph, vector):
    #one iteration of the power method
    #we assume the operator applies to the vector like the output of GraphLaplacian
    
    return GraphLaplacian(graph, vector)/np.sqrt(np.dot(GraphLaplacian(graph, vector), GraphLaplacian(graph, vector)))

In [71]:
#for the net we would like to use some random vector so that we have a good
#chance of having non trivial component in direction of largest eigenvector

def PowerMethod_iterate(iterations, graph, vector):
    for i in range(iterations):
        vector = PowerMethod(graph, vector)
    return vector

In [74]:
PowerMethod_iterate(5, graph=simple_graph, vector=np.array([ 1,1000, 0,2]))

array([ 0.55448772,  0.55448772,  0.27752   ,  0.55503999])

In [84]:
#first try at implementing net

#nonlinearity?
#fixed number of layers for iterations
#fixed subspace dimension for number of eigenvectors


def ClusterNet_1(Graph, layers, subspace_dim, vector=None):
    #takes in graph, computes Laplacian, then does powermethod
    #we end up with a list of k eigenvectors to do k-means on
    #we assume Graph given as a dictionary
    
    if vector==None:
        vector = np.ones(len(Graph)) #we initalize with function f==1
    
    eigenvectors = [[1]*len(vector)]*subspace_dim
    
    for i in range(subspace_dim): #this cannot be done in parallel
        eigenvectors[i] = PowerMethod_iterate(iterations = layers, graph=Graph, vector=vector)
        vector = vector - np.dot(vector, eigenvectors[i])
        print vector
        print eigenvectors[i]
        #now we must do gram-schmidt and subtract away this vector  
        
    return eigenvectors
        

In [86]:
ClusterNet_1(simple_graph, layers=10, subspace_dim=2)

[-0.96384417 -0.96384417 -0.96384417 -0.96384417]
[ 0.52101988  0.52101988  0.3339871   0.5878173 ]
[-2.85668392 -2.85668392 -2.85668392 -2.85668392]
[-0.52101988 -0.52101988 -0.3339871  -0.5878173 ]


[array([ 0.52101988,  0.52101988,  0.3339871 ,  0.5878173 ]),
 array([-0.52101988, -0.52101988, -0.3339871 , -0.5878173 ])]

In [62]:
[[]]*10


[[], [], [], [], [], [], [], [], [], []]